<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-04T21:02:34 IST" name="Suite" finished-at="2024-02-04T21:02:39 IST" duration-ms="4972">
    <groups>
      <group name="P0">
        <method signature="Logintestcases.validcredentialTestcaseOne(java.lang.reflect.Method)[pri:0, instance:seleniumframework.testcases.Logintestcases@1cf6d1be]" name="validcredentialTestcaseOne" class="seleniumframework.testcases.Logintestcases"/>
        <method signature="Logintestcases.validcredentialTestcasethree()[pri:0, instance:seleniumframework.testcases.Logintestcases@1cf6d1be]" name="validcredentialTestcasethree" class="seleniumframework.testcases.Logintestcases"/>
      </group> <!-- P0 -->
      <group name="P1">
        <method signature="Logintestcases.validcredentialTestcasetwo()[pri:1, instance:seleniumframework.testcases.Logintestcases@1cf6d1be]" name="validcredentialTestcasetwo" class="seleniumframework.testcases.Logintestcases"/>
      </group> <!-- P1 -->
    </groups>
    <test started-at="2024-02-04T21:02:34 IST" name="LoginwithValidcredentials" finished-at="2024-02-04T21:02:39 IST" duration-ms="4972">
      <class name="seleniumframework.testcases.Logintestcases">
        <test-method is-config="true" signature="setup()[pri:0, instance:seleniumframework.testcases.Logintestcases@1cf6d1be]" started-at="2024-02-04T21:02:23 IST" name="setup" finished-at="2024-02-04T21:02:34 IST" duration-ms="10564" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validcredentialTestcaseOne(java.lang.reflect.Method)[pri:0, instance:seleniumframework.testcases.Logintestcases@1cf6d1be]" started-at="2024-02-04T21:02:34 IST" name="validcredentialTestcaseOne" finished-at="2024-02-04T21:02:34 IST" duration-ms="13" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void seleniumframework.testcases.Logintestcases.validcredentialTestcaseOne(java.lang.reflect.Method)]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Cannot find elements when the XPath is null.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Cannot find elements when the XPath is null.
at org.openqa.selenium.internal.Require$ArgumentChecker.nonNull(Require.java:207)
at org.openqa.selenium.By$ByXPath.<init>(By.java:286)
at org.openqa.selenium.By.xpath(By.java:89)
at seleniumframework.testcases.Logintestcases.validcredentialTestcaseOne(Logintestcases.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validcredentialTestcaseOne -->
        <test-method signature="validcredentialTestcasethree()[pri:0, instance:seleniumframework.testcases.Logintestcases@1cf6d1be]" started-at="2024-02-04T21:02:35 IST" name="validcredentialTestcasethree" finished-at="2024-02-04T21:02:36 IST" duration-ms="1097" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validcredentialTestcasethree -->
        <test-method signature="validcredentialTestcasetwo()[pri:1, instance:seleniumframework.testcases.Logintestcases@1cf6d1be]" started-at="2024-02-04T21:02:36 IST" name="validcredentialTestcasetwo" finished-at="2024-02-04T21:02:39 IST" duration-ms="3057" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validcredentialTestcasetwo -->
      </class> <!-- seleniumframework.testcases.Logintestcases -->
    </test> <!-- LoginwithValidcredentials -->
  </suite> <!-- Suite -->
</testng-results>
